# Generated by Django 3.2.9 on 2021-12-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211214_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(blank=True, max_length=120, primary_key=True, serialize=False),
        ),
    ]
