# Generated by Django 3.2.9 on 2021-12-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0003_alter_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterModelTable(
            name='orders',
            table='Order',
        ),
    ]
