# Generated by Django 3.2.9 on 2021-12-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_seller'),
        ('orders', '0004_auto_20211215_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_items',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_items',
            field=models.ManyToManyField(null=True, to='products.Product'),
        ),
    ]
