# Generated by Django 3.2.9 on 2021-12-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price'),
        ('orders', '0005_auto_20211215_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_items',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
