# Generated by Django 3.2.9 on 2021-12-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orders_order_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Order'},
        ),
    ]
